spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:

server:
  port: 8088

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - circuitbreakers

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 8
        failure-rate-threshold: 20
        minimum-number-of-calls: 4
        wait-duration-in-open-state:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true

keycloak:
  auth:
    jwt-set-uri:

security:
  excluded:
    urls: /actuator/**