spring:
  application:
    name: alert-service
  kafka:
    bootstrap-servers:
      - localhost:9094
    consumer:
      group-id: wattwise-alert-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping:AlertingEvent:io.github.devcavin.wattwise.kafka.event.AlertingEvent
  datasource:
    url: jdbc:mariadb://localhost:3306/wattwise
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
        starttls:
          enable: false

server:
  port: 8087
